# Generated by Django 5.0.3 on 2024-03-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_image',
        ),
    ]
