# Generated by Django 5.0.3 on 2024-03-29 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_receipe_receipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Paragraph',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='receipe_description',
            new_name='paragraph_description',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='receipe_name',
            new_name='paragraph_name',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='receipe_view_count',
            new_name='paragraph_view_count',
        ),
    ]
